version: '3.8'

services:
  jenkins-connector:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_USERNAME=${JENKINS_USERNAME}
      - JENKINS_PASSWORD=${JENKINS_PASSWORD}
      - JENKINS_CREDENTIALS=${JENKINS_CREDENTIALS}
